# Generated by Django 5.1.7 on 2025-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Название производителя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название товара'),
        ),
        migrations.AddConstraint(
            model_name='maker',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_maker'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'maker', 'category', 'color'), name='unique_product'),
        ),
    ]
