# Generated by Django 5.1.7 on 2025-03-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_maker_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=None, upload_to='photo/%Y/%m/%d', verbose_name='Фото товара'),
        ),
    ]
