# Generated by Django 5.1.7 on 2025-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(default='', verbose_name='Полное описание товара'),
        ),
    ]
