# Generated by Django 5.1.7 on 2025-03-25 15:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Полное описание товара'),
        ),
    ]
